version: '3.8'
services:
  lab-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lab-service
    ports:
      - '8085:8085'
    environment:
      - NODE_ENV=development
      - PORT=8085
      - MONGO_URI_LOCAL=mongodb://mongo:27017/lab-service
      - MONGO_URI=mongodb+srv://<user>:<pass>@cluster0.mongodb.net/lab-service?retryWrites=true&w=majority
      - JWT_SECRET=Xy9vA$23k!ZbLp@76JrQmEwTn$HsDfGuIoPaLzXcVbNmQwErTyUiOp1234567890
      - SERVICE_KEY=a7b9c2d8e4f0g1h2i3j4k5l6m7n8o9p0q1r2s3t4
      - USER_SERVICE_URL=http://user-service:5000
      - APPOINTMENT_SERVICE_URL=http://appointment-service:8083
      - NOTIFICATION_SERVICE_URL=http://notification-service:8081
      - API_GATEWAY_URL=http://api-gateway:8080
      - LOG_LEVEL=info
      - PROMETHEUS_URL=http://prometheus:9090
      - GRAFANA_URL=http://grafana:3000
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo
      - rabbitmq
      - prometheus
    networks:
      - healthcare-net
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=lab-service
    networks:
      - healthcare-net
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - healthcare-net
  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: prometheus
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    networks:
      - healthcare-net
volumes:
  mongo-data:
  rabbitmq-data:
  prometheus-data:
networks:
  healthcare-net:
    driver: bridge